=== bontiv/vtherm-website/devicesdb/devices.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://www.versatile-thermostat.org/devices.schema.json",
    "title": "Device database",
    "description": "Database of compatible devices with Versatile Thermostat",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "manufacturer": {
                "type": "string",
                "description": "Name of the manufacturer"
            },
            "model": {
                "type": "string",
                "description": "Model number"
            },
            "img": {
                "type": "string",
                "description": "Link to a picture of device. It can be absolute link or relative and image in public/img folder."
            },
            "slug": {
                "type": "string",
                "description": "Sub folder where the device definition is located. It will also be use as slug in URL."
            },
            "state": {
                "enum": [
                    "supported",
                    "community",
                    "unsupported",
                    "partially"
                ],
                "description": "supported: Maintainer supported device | community: report as working by the community | partially: Work with limitations | unsupported: not supported device"
            },
            "title": {
                "type": "string",
                "description": "Title for this device"
            },
            "type": {
                "enum": [
                    "trv",
                    "climate",
                    "electric"
                ],
                "description": "Type of device"
            }
        },
        "required": [
            "manufacturer",
            "model",
            "img",
            "slug",
            "state",
            "type"
        ]
    }
}

=== bontiv/vtherm-website/devicesdb/devices.json
[
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/TRVZB.png",
        "manufacturer": "Sonoff",
        "model": "TRVZB",
        "slug": "sonoff-trvzb",
        "state": "supported",
        "type": "trv"
    },
    {
        "img": "https://www.robot-advance.com/ori-thermostat-de-radiateur-w600-aqara-6436.jpg",
        "manufacturer": "Aqara",
        "model": "W600",
        "slug": "aqara-w600",
        "state": "supported",
        "title": "Aqara W600",
        "type": "trv"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/CoZB_dha.png",
        "manufacturer": "Eutronic",
        "model": "CoZB_dha",
        "slug": "over-climate-valve",
        "state": "community",
        "title": "Eutronic Comet",
        "type": "trv"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/COZB0001.png",
        "manufacturer": "Eutronic",
        "model": "COZB0001",
        "slug": "over-climate-valve",
        "state": "community",
        "type": "trv"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/014G2461.png",
        "manufacturer": "Danfoss",
        "model": "014G2461",
        "slug": "over-climate",
        "state": "partially",
        "title": "Danfoss Ally",
        "type": "trv"
    },
    {
        "img": "https://www.zigbee2mqtt.io/images/devices/SIN-4-FP-20.png",
        "manufacturer": "NodOn",
        "model": "SIN-4-FP-20",
        "slug": "over-switch",
        "state": "supported",
        "type": "electric"
    },
    {
        "img": "/img/tuya-ac.jpg",
        "title": "Tuya WIFI",
        "manufacturer": "Tuya",
        "model": "",
        "slug": "tuya-wifi",
        "state": "supported",
        "type": "climate"
    },
    {
        "img": "https://images.squarespace-cdn.com/content/v1/57d112cb9f7456d72f62cd0f/1937c67e-c931-40b9-a66c-ae0fea0a4d43/heatzy-pilote-co%CC%82te%CC%81.jpg",
        "manufacturer": "heatzy",
        "model": "pilote",
        "state": "supported",
        "type": "electric",
        "slug": "heatzy"
    },
    {
        "manufacturer": "MOES",
        "model": "UFO-R11",
        "img": "https://www.zigbee2mqtt.io/images/devices/UFO-R11.png",
        "state": "community",
        "type": "electric",
        "slug": "smartir"
    }
]
